version: "3"

services:
    database:
        image: mongo
        ports: 
            - "27017:27017"
    backend:
        image: skyg4mb/bescenerecon:latest
        ports:
            - "1337:1337"
        volumes:
            - "./config:/app/config"
            - "./certs:/app/certs"
        links:
            - database
        depends_on:
            - database
    client: 
        image: skyg4mb/scenerecon:latest
        ports: 
            - "80:80"
        links:
            - backend
        depends_on:
            - backend
